= pick

Full-featured server-driven content negotiation for HTTP, in Clojure.

[WARNING]
--
STATUS: Alpha. Still fresh, some development remaining.
--

== Quick Start

Suppose you are writing a web service and want to provide proactive content negotiation based on the accept headers in the client request. Suppose also that have established which variants you want to choose between.

A variant is represented as a Clojure map:

[source,clojure]
----
{:juxt.http/content-type {:juxt.http/type "text"
                          :juxt.http/subtype "html"
                          :juxt.http/parameter-map {"charset" "utf-8"}
                          }
 :juxt.http/content-encoding "gzip,deflate"
 :juxt.http/content-language "en-US"
 }
----

[TIP]
--
If you prefer to specify these values as string literals, use our https://github.com/juxt/reap[reap] library.

[source,clojure]
----
(require '[juxt.reap.alpha.decoders :as reap]

{:juxt.http/content-type (reap/content-type "text/html;charset=utf-8")
 :juxt.http/content-encoding (reap/content-encoding "gzip,deflate")
 :juxt.http/content-language (reap/content-language "en-US")
 }
----

--

You can use *pick* to select the variant that is most acceptable to the user agent. Here's how:

[source,clojure]
----
(require '[juxt.pick.apache :refer [select-variant]])

(select-variant
 {:juxt.http/request-headers {…} ; Parseding request headers
  :juxt.http/variants […] ; Collection of maps, each representing a possible variant
  :juxt.http/explain? false})
=>
{:juxt.http/variant {…}; variant chosen
 :juxt.http/vary […] ; request headers used in the determination
 }

----

== Introduction

Content negotiation is a feature of HTTP that allows different 'representations'
to be served from the same URI.

*pick* is a Clojure library implementing Apache's _de-facto_ http://httpd.apache.org/docs/current/en/content-negotiation.html#algorithm[content negotiation algorithm].

=== Problem Statement

The web is the most dominant form of information exchange on the
internet. Content negotiation is one of the primary ways that the web is
inclusive, supporting a wide range of user agents and other software-based
clients.

It improves performance, by allowing the compression of content for optimising
network bandwidth and by cache integration.

And since content negotiation allows for gradual migration from old to new data
formats it enables graceful and continuous improvement, balancing the needs for
both innovation and solid dependability.

However, while content negotiation is often used for static resources, and is
well implemented by web servers such as Apache's httpd and nginx, it is often
missing from, or poorly implemented by, the majority of web libraries and
frameworks.

=== Alternatives

Most Clojure alternatives only deal with media-types, and perhaps charsets. Note
that *pick* fully implements _all_ proactive (server-driven) content negotiation
rules contained in https://tools.ietf.org/html/rfc7231[RFC 7231], including
media-types, charsets, encodings, languages, wildcards, qvalues and precedence
rules. Where not prescribed specifically by the RFC, *pick* adopts the
_de-facto_ decisions made by the Apache httpd engine.

https://github.com/ngrunwald/ring-middleware-format[ring-middleware-format] and
Metosin's https://github.com/metosin/muuntaja[Muuntaja] library negotiate
media-types and charsets, and perform automatic decoding/encoding of
request/response bodies

[CAUTION]
--
*pick* only provides the decision logic of which variant to select,
given the context of an HTTP request and a set of variants to choose between.

It
does *not* include support for format transformation or coercion, which is _not
in scope_ for this library.
--

https://github.com/clojure-liberator/liberator/commits/master[Liberator]

https://github.com/juxt/yada[yada]


== Documentation

NOTE: TBD

=== Selecting a variant

Use the `juxt.pick.alpha.apache/select-variant` function.

NOTE: Document the argument map

=== Media-types

=== Charsets

=== Encodings

=== Languages

== References

https://tools.ietf.org/html/rfc7231[RFC 7231] is the normative standard on content negotiation.

This https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[MDN guide on content negotiation from Mozilla] is very informative.
